spring:  application:    name: CONFIG-SERVER  cloud:    config:      server:        git:          uri: https://github.com/anandsaraswa/cloud-config-server-ticket          default-label: main          clone-on-startup: true
server:
  port: 9999
  