
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:    gateway:      routes:      - id: account-service
        uri: lb://ACCOUNT-SERVICE
        predicates:          - Path=/account/**
        filters:        - name: CircuitBreaker
          args:            name: ACCOUNT-SERVICE
            fallbackuri: forward:/fallback/account
        - name: JwtAuthenticationFilterFactory
          args:
            name: ACCOUNT-SERVICE
       
      - id: ticket-service
        uri: lb://TICKET-SERVICE
        predicates:
          - Path=/ticket/**
        filters:
        - name: JwtAuthenticationFilterFactory
          args:
            name: TICKET-SERVICE
       
      - id: authenticate-service
        uri: lb://AUTHENTICATE-SERVICE
        predicates:
          - Path=/secure/**
        filters:
        - name: JwtAuthenticationFilterFactory
          args:
            name: AUTHENTICATE-SERVICE
        - name: CircuitBreaker
          args:
            name: AUTHENTICATE-SERVICE
            fallbackuri: forward:/fallback/authenticate
        
          
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000  
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        

    
server:
  port: 8787
  
  
