server:
  port: 9113
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_manage_schema
    username: root
    password: 12311
  jpa:    show-sql: true
    properties:      hibernate:
        format_sql:true
  application:
    name: AUTHENTICATE-SERVICE
