server:
  port: 9111
spring:
  h2:
    console:
      enabled: true
  datasource:    url: jdbc:h2:mem:testdb
  application:    name: ACCOUNT-SERVICE
  zipkin:
    base-url: http://localhost:9411/