server:
  port: 9112
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  application:
    name: TICKET-SERVICE
  zipkin:    base-url: http://localhost:9411/
    